import { useCallback, useEffect, useRef, useState } from "react";
import { api } from "../api";
import { Badge } from "../components/Badge";
import { useI18n } from "../i18n";
import type { AnalysisResult, JobStatus } from "../types";

type Stage = "idle" | "uploading" | "analyzing" | "done" | "error";

interface AuthSignal {
  name: string;
  description: string;
  verdict: "clean" | "suspicious" | "manipulated" | "unknown";
  confidence: number; // 0-1
  detail?: string;
}

function deriveAuthSignals(result: AnalysisResult): AuthSignal[] {
  const sigs: AuthSignal[] = [];
  const signals = result.signals;

  const statusIs = (s: unknown, val: string) => (s as string) === val;

  // Voice clone detection
  const clone = signals.voice_clone ?? signals.clone ?? signals.deepfake;
  if (clone) {
    sigs.push({
      name: "AI Voice Clone Detection",
      description: "Detects if voice was generated by AI synthesis (TTS/voice conversion)",
      verdict: statusIs(clone.status, "detected") ? "manipulated" :
               statusIs(clone.status, "clear") ? "clean" : "unknown",
      confidence: clone.score ?? (statusIs(clone.status, "detected") ? 0.85 : 0.1),
      detail: clone.label ?? clone.detail ?? undefined,
    });
  }

  // Audio manipulation / editing artifacts
  const edit = signals.audio_edit ?? signals.splicing ?? signals.tampering;
  if (edit) {
    sigs.push({
      name: "Audio Splice & Edit Detection",
      description: "Checks for cut-and-paste audio editing, silence insertion or temporal artifacts",
      verdict: statusIs(edit.status, "detected") ? "manipulated" : statusIs(edit.status, "clear") ? "clean" : "unknown",
      confidence: edit.score ?? (statusIs(edit.status, "detected") ? 0.78 : 0.1),
      detail: edit.detail ?? undefined,
    });
  }

  // Background noise / environment consistency
  const bg = signals.background ?? signals.noise ?? signals.environment;
  if (bg) {
    sigs.push({
      name: "Environment Consistency",
      description: "Detects inconsistent background noise indicating studio-generated content",
      verdict: statusIs(bg.status, "detected") ? "suspicious" : statusIs(bg.status, "clear") ? "clean" : "unknown",
      confidence: bg.score ?? 0.5,
      detail: bg.detail ?? undefined,
    });
  }

  // Prosody / human speech patterns
  const prosody = signals.prosody ?? signals.naturalness ?? signals.rhythm;
  if (prosody) {
    sigs.push({
      name: "Prosody & Naturalness",
      description: "Checks if speech rhythm, intonation, and breathing match organic human speech",
      verdict: statusIs(prosody.status, "detected") ? "suspicious" :
               statusIs(prosody.status, "clear") ? "clean" : "unknown",
      confidence: prosody.score ?? 0.5,
      detail: prosody.detail ?? undefined,
    });
  }

  // MFCC / spectral features
  const spectral = signals.spectral ?? signals.mfcc ?? signals.frequency;
  if (spectral) {
    sigs.push({
      name: "Spectral Fingerprint",
      description: "Analyzes frequency patterns for codec artifacts typical in AI-generated audio",
      verdict: statusIs(spectral.status, "detected") ? "manipulated" : statusIs(spectral.status, "clear") ? "clean" : "unknown",
      confidence: spectral.score ?? 0.5,
      detail: spectral.detail ?? undefined,
    });
  }

  // Transcription-based (content scam signals)
  const content = signals.content ?? signals.scam ?? signals.keywords;
  if (content) {
    sigs.push({
      name: "Content Authenticity",
      description: "Checks spoken content for scripted scam language, forced/unnatural phrasing",
      verdict: statusIs(content.status, "detected") ? "suspicious" : statusIs(content.status, "clear") ? "clean" : "unknown",
      confidence: content.score ?? (result.risk.score / 100),
      detail: content.detail ?? undefined,
    });
  }

  // If no signals, synthesize from risk score and red flags
  if (sigs.length === 0) {
    const riskScore = result.risk.score / 100;
    const hasCloneFlag = result.red_flags.some(
      (f) => f.id.includes("clone") || f.id.includes("deepfake") || f.id.includes("synthetic"),
    );
    const hasEditFlag = result.red_flags.some(
      (f) => f.id.includes("edit") || f.id.includes("tamper") || f.id.includes("splice"),
    );

    sigs.push({
      name: "AI Voice Synthesis Detection",
      description: "Overall assessment of AI-generated or cloned voice patterns",
      verdict: hasCloneFlag ? "manipulated" : riskScore > 0.6 ? "suspicious" : "clean",
      confidence: riskScore,
      detail: hasCloneFlag ? "AI-generated voice patterns detected" : "No cloning artifacts detected",
    });

    sigs.push({
      name: "Audio Integrity Check",
      description: "Temporal and spectral consistency of the audio file",
      verdict: hasEditFlag ? "manipulated" : riskScore > 0.7 ? "suspicious" : "clean",
      confidence: Math.max(0.1, riskScore * 0.9),
      detail: hasEditFlag ? "Editing artifacts detected" : "Audio appears unmodified",
    });

    sigs.push({
      name: "Content Pattern Analysis",
      description: "Script-like language, coercion phrases, and urgency signals",
      verdict: riskScore > 0.7 ? "suspicious" : "clean",
      confidence: riskScore,
      detail: `${result.red_flags.length} suspicious patterns found`,
    });
  }

  return sigs;
}

function computeOverallVerdict(signals: AuthSignal[], riskScore: number) {
  const manipulated = signals.filter((s) => s.verdict === "manipulated").length;
  const suspicious = signals.filter((s) => s.verdict === "suspicious").length;

  if (manipulated >= 1 || riskScore >= 70) return "manipulated" as const;
  if (suspicious >= 2 || riskScore >= 45) return "suspicious" as const;
  return "authentic" as const;
}

const VERDICT_META = {
  authentic:   { icon: "✅", label: "Authentic",   color: "var(--emerald)", badge: "emerald" },
  suspicious:  { icon: "⚠️",  label: "Suspicious",  color: "var(--amber)",   badge: "amber" },
  manipulated: { icon: "🚨", label: "Manipulated / Cloned", color: "var(--rose)", badge: "rose" },
};

const SIGNAL_VERDICT_META = {
  clean:       { color: "var(--emerald)", badge: "emerald", label: "Clean" },
  suspicious:  { color: "var(--amber)",   badge: "amber",   label: "Suspicious" },
  manipulated: { color: "var(--rose)",    badge: "rose",    label: "Manipulated" },
  unknown:     { color: "var(--text-4)",  badge: "neutral", label: "Unknown" },
};

export function MediaAuthPage() {
  const { t } = useI18n();
  const [stage, setStage] = useState<Stage>("idle");
  const [file, setFile] = useState<File | null>(null);
  const [drag, setDrag] = useState(false);
  const [progress, setProgress] = useState(0);
  const [progressMsg, setProgressMsg] = useState("Uploading…");
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const pollRef = useRef<number | null>(null);

  useEffect(() => () => { if (pollRef.current) clearTimeout(pollRef.current); }, []);

  const poll = useCallback(async (jobId: string) => {
    const clear = () => { if (pollRef.current) clearTimeout(pollRef.current); pollRef.current = null; };
    try {
      const st: JobStatus = await api.getJob(jobId);
      if (st.status === "completed" && st.result) {
        clear();
        setResult(st.result);
        setStage("done");
        return;
      }
      if (st.status === "failed") {
        clear();
        setError(st.error || "Analysis failed");
        setStage("error");
        return;
      }
      setProgress(st.progress);
      if (st.message) setProgressMsg(st.message);
      pollRef.current = setTimeout(() => poll(jobId), 800);
    } catch (e) {
      clear();
      setError(e instanceof Error ? e.message : "Error");
      setStage("error");
    }
  }, []);

  const analyse = async (f: File) => {
    setFile(f);
    setError(null);
    setResult(null);
    setStage("uploading");
    setProgress(0.02);
    setProgressMsg("Uploading file…");
    try {
      const created = await api.uploadMedia(f);
      setStage("analyzing");
      setProgress(0.1);
      setProgressMsg("Extracting audio features…");
      await poll(created.job_id);
    } catch (e) {
      setError(e instanceof Error ? e.message : t("err.network"));
      setStage("error");
    }
  };

  const pickFile = (f: File | undefined) => { if (f) analyse(f); };
  const reset = () => { setStage("idle"); setFile(null); setResult(null); setError(null); setProgress(0); };

  // Derived
  const authSignals = result ? deriveAuthSignals(result) : [];
  const overallVerdict = result ? computeOverallVerdict(authSignals, result.risk.score) : null;
  const verdictMeta = overallVerdict ? VERDICT_META[overallVerdict] : null;

  const isProcessing = stage === "uploading" || stage === "analyzing";

  return (
    <div className="page">
      <div className="page-head">
        <h1>{t("media_auth.title")}</h1>
        <p>{t("media_auth.sub")}</p>
      </div>

      {/* Upload area */}
      {stage === "idle" && (
        <div className="card">
          <div
            className={`dropzone${drag ? " over" : ""}`}
            style={{ minHeight: 180 }}
            onClick={() => fileRef.current?.click()}
            onDragOver={(e) => { e.preventDefault(); setDrag(true); }}
            onDragLeave={() => setDrag(false)}
            onDrop={(e) => { e.preventDefault(); setDrag(false); pickFile(e.dataTransfer.files[0]); }}
          >
            <input
              ref={fileRef}
              type="file"
              accept="audio/*,video/*,.wav,.mp3,.m4a,.ogg,.flac,.mp4,.mov,.webm,.amr"
              hidden
              onChange={(e) => pickFile(e.target.files?.[0])}
            />
            <div className="dropzone-icon" style={{ fontSize: 40 }}>🎧</div>
            <div className="dropzone-label" style={{ fontSize: 15, fontWeight: 600 }}>
              Drop an audio or video file to check authenticity
            </div>
            <div className="dropzone-sub">WAV · MP3 · M4A · OGG · FLAC · MP4 · MOV · WEBM · AMR</div>
          </div>

          {/* Feature highlights */}
          <div className="grid grid-3" style={{ marginTop: 20 }}>
            {[
              { icon: "🤖", title: "AI Clone Detection", desc: "Detects TTS and voice conversion artifacts using MFCC, GAN fingerprints, and spectral analysis" },
              { icon: "✂️", title: "Edit & Splice Detection", desc: "Identifies cut-and-paste audio editing, silence gaps, and temporal inconsistencies" },
              { icon: "🔍", title: "Content Analysis", desc: "Checks spoken content for scripted scam language, coercion patterns, and synthetic phrasing" },
            ].map((f) => (
              <div key={f.title} style={{ padding: "14px 16px", background: "var(--bg-2)", borderRadius: "var(--r-md)", border: "1px solid var(--border)" }}>
                <div style={{ fontSize: 22, marginBottom: 8 }}>{f.icon}</div>
                <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>{f.title}</div>
                <div style={{ fontSize: 12, color: "var(--text-3)", lineHeight: 1.5 }}>{f.desc}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Processing */}
      {isProcessing && (
        <div className="card" style={{ textAlign: "center", padding: "40px 20px" }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 12, marginBottom: 16 }}>
            <div className="spinner" style={{ width: 32, height: 32, borderWidth: 3 }} />
            <div>
              <div style={{ fontWeight: 600, fontSize: 15 }}>
                {stage === "uploading" ? "Uploading file…" : "Analysing authenticity…"}
              </div>
              <div style={{ fontSize: 12, color: "var(--text-3)", marginTop: 3 }}>{progressMsg}</div>
            </div>
          </div>
          {file && (
            <div className="file-chip" style={{ justifyContent: "center", display: "inline-flex" }}>
              🎵 {file.name} · {(file.size / 1024 / 1024).toFixed(1)} MB
            </div>
          )}
          <div className="progress" style={{ maxWidth: 400, margin: "16px auto 0" }}>
            <div className="progress-bar" style={{ width: `${Math.round(progress * 100)}%` }} />
          </div>
          <div className="progress-label" style={{ textAlign: "center" }}>{Math.round(progress * 100)}%</div>
          <div style={{ marginTop: 16, fontSize: 12, color: "var(--text-4)" }}>
            Running DWANI XLS-R · MFCC · Prosody analysis · GAN fingerprint detection…
          </div>
        </div>
      )}

      {/* Error */}
      {stage === "error" && (
        <div className="card">
          <div className="error-banner">{error}</div>
          <button className="btn btn-secondary btn-sm" onClick={reset} style={{ marginTop: 8 }}>Try Again</button>
        </div>
      )}

      {/* Results */}
      {stage === "done" && result && verdictMeta && (
        <>
          {/* Overall verdict banner */}
          <div
            className={`auth-check-result verdict-${overallVerdict}`}
            style={{ border: `1.5px solid`, borderColor: verdictMeta.color + "44" }}
          >
            <div className="auth-check-header">
              <span className="auth-verdict-icon">{verdictMeta.icon}</span>
              <div style={{ flex: 1 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 4 }}>
                  <span style={{ fontSize: 18, fontWeight: 700, color: verdictMeta.color }}>{verdictMeta.label}</span>
                  <Badge tone={verdictMeta.badge}>
                    Risk Score: {Math.round(result.risk.score)}/100
                  </Badge>
                </div>
                <div style={{ fontSize: 13, color: "var(--text-2)" }}>
                  {overallVerdict === "authentic" && "No significant signs of AI generation or audio manipulation detected."}
                  {overallVerdict === "suspicious" && "Some suspicious patterns detected. Human review recommended before trusting this content."}
                  {overallVerdict === "manipulated" && "Strong evidence of AI voice cloning or audio manipulation. This file should NOT be trusted."}
                </div>
                {file && (
                  <div className="file-chip" style={{ marginTop: 8 }}>
                    🎵 {file.name} · {(file.size / 1024 / 1024).toFixed(1)} MB
                    {result.duration_seconds != null && <span> · {Math.round(result.duration_seconds)}s</span>}
                    {result.language && <span> · {result.language}</span>}
                  </div>
                )}
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 8, alignSelf: "flex-start" }}>
                <button className="btn btn-ghost btn-sm" onClick={reset}>↺ New Check</button>
                <a className="btn btn-danger btn-sm" href="tel:1930">📞 Report 1930</a>
              </div>
            </div>

            {/* Authenticity signals */}
            <div className="auth-check-section">
              <div className="auth-check-section-title">Authenticity Signals</div>
              {authSignals.map((sig) => {
                const meta = SIGNAL_VERDICT_META[sig.verdict];
                const pct = Math.round(sig.confidence * 100);
                return (
                  <div className="auth-signal-row" key={sig.name}>
                    <div style={{ width: 130, flexShrink: 0 }}>
                      <Badge tone={meta.badge}>{meta.label}</Badge>
                    </div>
                    <div className="auth-signal-name">
                      <div style={{ fontWeight: 500, fontSize: 13 }}>{sig.name}</div>
                      <div style={{ fontSize: 11.5, color: "var(--text-4)", marginTop: 1 }}>{sig.description}</div>
                    </div>
                    <div className="auth-signal-bar">
                      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                        <div className="bar-track" style={{ flex: 1 }}>
                          <div
                            className="bar-fill"
                            style={{
                              width: `${pct}%`,
                              background: meta.color,
                            }}
                          />
                        </div>
                        <span style={{ fontSize: 11.5, color: "var(--text-3)", minWidth: 32, textAlign: "right" }}>
                          {pct}%
                        </span>
                      </div>
                      {sig.detail && (
                        <div style={{ fontSize: 11, color: "var(--text-4)", marginTop: 3 }}>{sig.detail}</div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Red flags from existing analysis */}
            {result.red_flags.length > 0 && (
              <div className="auth-check-section">
                <div className="auth-check-section-title">Detected Threat Indicators</div>
                <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  {result.red_flags.slice(0, 8).map((f) => (
                    <div key={f.id} style={{ display: "flex", alignItems: "flex-start", gap: 8, padding: "6px 0" }}>
                      <span
                        className="status-dot"
                        style={{
                          marginTop: 4, flexShrink: 0,
                          background: f.severity === "critical" ? "var(--rose)" : f.severity === "warning" ? "var(--amber)" : "var(--blue)",
                          boxShadow: f.severity === "critical" ? "0 0 6px var(--rose)" : "none",
                        }}
                      />
                      <div>
                        <div style={{ fontSize: 13, fontWeight: 500 }}>
                          {typeof f.title === "string" ? f.title : (f.title as { en: string }).en}
                        </div>
                        <div style={{ fontSize: 12, color: "var(--text-3)", marginTop: 1 }}>
                          {typeof f.detail === "string" ? f.detail : (f.detail as { en: string }).en}
                        </div>
                      </div>
                      <Badge tone={f.severity === "critical" ? "rose" : f.severity === "warning" ? "amber" : "blue"}>
                        {f.severity}
                      </Badge>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Transcript if available */}
            {result.transcript && (
              <div className="auth-check-section">
                <div className="auth-check-section-title">Transcription</div>
                <pre style={{ fontSize: 12.5, whiteSpace: "pre-wrap", wordBreak: "break-word", maxHeight: 200, overflowY: "auto", color: "var(--text-2)" }}>
                  {result.transcript}
                </pre>
              </div>
            )}

            {/* Recommended actions */}
            <div className="auth-check-section">
              <div className="auth-check-section-title">Recommended Actions</div>
              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                {overallVerdict === "manipulated" && <>
                  <div style={{ fontSize: 13, color: "var(--text-2)" }}>🚨 <strong>Do not trust</strong> this audio/video. It shows strong signs of AI generation.</div>
                  <div style={{ fontSize: 13, color: "var(--text-2)" }}>📞 Call <strong>1930</strong> or file a complaint at <a href="https://cybercrime.gov.in" target="_blank" rel="noreferrer">cybercrime.gov.in</a></div>
                  <div style={{ fontSize: 13, color: "var(--text-2)" }}>💾 Preserve the original file and any associated metadata as evidence</div>
                </>}
                {overallVerdict === "suspicious" && <>
                  <div style={{ fontSize: 13, color: "var(--text-2)" }}>⚠️ <strong>Exercise caution.</strong> Verify through alternate channels before acting.</div>
                  <div style={{ fontSize: 13, color: "var(--text-2)" }}>📋 Document the communication and relevant context</div>
                </>}
                {overallVerdict === "authentic" && <>
                  <div style={{ fontSize: 13, color: "var(--text-2)" }}>✅ No AI manipulation detected. Standard content safety protocols apply.</div>
                  <div style={{ fontSize: 13, color: "var(--text-2)" }}>ℹ️ Always verify identity through independent means for sensitive matters.</div>
                </>}
              </div>
            </div>
          </div>

          <div className="result-actions" style={{ marginTop: 16 }}>
            <button className="btn btn-secondary" onClick={reset}>↺ Check Another File</button>
            {result.transcript && (
              <button className="btn btn-ghost" onClick={() => {
                const blob = new Blob([result.transcript!], { type: "text/plain" });
                const url = URL.createObjectURL(blob);
                const a = document.createElement("a");
                a.href = url; a.download = `auth-check-${result.scan_id}.txt`; a.click();
                URL.revokeObjectURL(url);
              }}>⤓ Download Transcript</button>
            )}
          </div>
        </>
      )}
    </div>
  );
}
